FROM node:22-alpine

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN npm install -g bun

RUN bun install
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

CMD ["bun", "run", "start:web"]