name: Deploy the Backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_ID}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build the image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: itzraghavv/docker-repo:${{github.sha}}

      - name: Deploy to VM
        env:
          SSH_PRIVATE_KEY: ${{github.SSH_PRIVATE_KEY}}
          SSH_HOST: ${{github.SSH_KEY}}
          SSH_USER: ${{github.SSH_HOST}}

        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/docker_repo_key
          chmod 600 ~/.ssh/docker_repo_key
          echo -e "Host ec2\n\tHostName $SSH_HOST\n\tUser $SSH_USER\n\tIdentityFile ~/.ssh deploy_key\n\tStrictHostKeyChecking no" > ~/.ssh/config
