name: Deploy the Backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_ID}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build the image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: itzraghavv/docker-repo:${{github.sha}}
