name: Deploy the Frontend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_ID}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: itzraghavv/repo-fe:${{github.sha}}

      - name: Deploy to VM
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_USER: ${{secrets.SSH_USER}}

        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/docker_repo_key
          chmod 600 ~/.ssh/docker_repo_key
          echo -e "Host ec2\n\tHostName $SSH_HOST\n\tUser $SSH_USER\n\tIdentityFile ~/.ssh/docker_repo_key\n\tStrictHostKeyChecking no" > ~/.ssh/config
          ssh ec2 << EOF 
          echo SSH connection success
          docker rm -f repo-fe 2>/dev/null || true
          docker pull itzraghavv/repo-fe:${{ github.sha }}
          docker run --name repo-fe -d -p 3000:3000 itzraghavv/repo-fe:${{ github.sha }}
          docker ps 
          EOF
